schema: ./src/gql-schema.json
documents: ./src/**/*.graphql
overwrite: true
generates:
  ./src/app/graphql.types.ts:
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
